FROM ubuntu:latest
RUN apt-get update
RUN apt-get install -y lsb-release ca-certificates apt-transport-https software-properties-common 
RUN add-apt-repository -y ppa:ondrej/php
RUN apt-get update
#RUN apt-get install -y php
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get -qq install -y php
ENTRYPOINT ["tail", "-f", "/dev/null"]
